spring:
  application:
    name: my-neat-little-app
  datasource:
    url: jdbc:h2:./camunda-h2-db
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
server.port: 8081
