version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  elasticsearch:
    image: elasticsearch:7.9.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node